apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  creationTimestamp: null
  name: gitops-configurer.packages.kadras.io.0.0.0
spec:
  licenses:
  - Apache 2.0
  refName: gitops-configurer.packages.kadras.io
  releaseNotes: https://github.com/kadras-io/gitops-configurer/releases
  releasedAt: null
  template:
    spec:
      deploy:
      - kapp: {}
      fetch:
      - git: {}
      template:
      - ytt:
          paths:
          - config
      - kbld: {}
  valuesSchema:
    openAPIv3: {}
  version: 0.0.0

---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  creationTimestamp: null
  name: gitops-configurer.packages.kadras.io
spec:
  categories:
  - gitops
  displayName: gitops-configurer
  longDescription: Simplify onboarding of GitOps workflows based on Carvel or Flux.
  maintainers:
  - name: Thomas Vitale
  providerName: Kadras
  shortDescription: Simplify onboarding of GitOps workflows.
  supportDescription: Go to https://kadras.io for documentation and https://github.com/kadras-io/gitops-configurer
    for community support.

---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  annotations:
    kctrl.carvel.dev/local-fetch-0: .
  creationTimestamp: null
  name: gitops-configurer
spec:
  packageRef:
    refName: gitops-configurer.packages.kadras.io
    versionSelection:
      constraints: 0.0.0
  serviceAccountName: kadras-install-sa
status:
  conditions: null
  friendlyDescription: ""
  observedGeneration: 0
